FROM node:14-alpine
WORKDIR /usr
COPY package.json ./
COPY src ./src
COPY tsconfig.json ./
RUN ls -a
RUN npm install
RUN npm run build
## this is stage two , where the app actually runs
FROM node:14-alpine
WORKDIR /usr
COPY package.json ./
RUN npm install --only=production
COPY --from=0 /usr/lib .
RUN npm install pm2 -g
EXPOSE 80
CMD ["pm2-runtime","app.js"]