\connect bit;

DELETE FROM bit.gun;
INSERT INTO bit.gun (id, gun_name) VALUES (1, '417');
INSERT INTO bit.gun (id, gun_name) VALUES (2, '5.7 USG');
INSERT INTO bit.gun (id, gun_name) VALUES (3, '552 Commando');
INSERT INTO bit.gun (id, gun_name) VALUES (4, '556xi');
INSERT INTO bit.gun (id, gun_name) VALUES (5, '6P41');
INSERT INTO bit.gun (id, gun_name) VALUES (6, '9mm C1');
INSERT INTO bit.gun (id, gun_name) VALUES (7, '9x19 VSN');
INSERT INTO bit.gun (id, gun_name) VALUES (8, 'AK-12');
INSERT INTO bit.gun (id, gun_name) VALUES (9, 'AR33');
INSERT INTO bit.gun (id, gun_name) VALUES (10, 'AUG A2');
INSERT INTO bit.gun (id, gun_name) VALUES (11, 'C8-SFW');
INSERT INTO bit.gun (id, gun_name) VALUES (12, 'CAMRS');
INSERT INTO bit.gun (id, gun_name) VALUES (13, 'F2');
INSERT INTO bit.gun (id, gun_name) VALUES (14, 'FMG-9');
INSERT INTO bit.gun (id, gun_name) VALUES (15, 'G36C');
INSERT INTO bit.gun (id, gun_name) VALUES (16, 'G8A1');
INSERT INTO bit.gun (id, gun_name) VALUES (17, 'GSH 18');
INSERT INTO bit.gun (id, gun_name) VALUES (18, 'L85A2');
INSERT INTO bit.gun (id, gun_name) VALUES (19, 'LFP586');
INSERT INTO bit.gun (id, gun_name) VALUES (20, 'M1014');
INSERT INTO bit.gun (id, gun_name) VALUES (21, 'M45 MEUSOC');
INSERT INTO bit.gun (id, gun_name) VALUES (22, 'M590A1');
INSERT INTO bit.gun (id, gun_name) VALUES (23, 'M870');
INSERT INTO bit.gun (id, gun_name) VALUES (24, 'MP5');
INSERT INTO bit.gun (id, gun_name) VALUES (25, 'MP5K');
INSERT INTO bit.gun (id, gun_name) VALUES (26, 'MP7');
INSERT INTO bit.gun (id, gun_name) VALUES (27, 'Mk1 9mm');
INSERT INTO bit.gun (id, gun_name) VALUES (28, 'OTs-03');
INSERT INTO bit.gun (id, gun_name) VALUES (29, 'P12');
INSERT INTO bit.gun (id, gun_name) VALUES (30, 'P226 Mk 25');
INSERT INTO bit.gun (id, gun_name) VALUES (31, 'P9');
INSERT INTO bit.gun (id, gun_name) VALUES (32, 'P90');
INSERT INTO bit.gun (id, gun_name) VALUES (33, 'PMM');
INSERT INTO bit.gun (id, gun_name) VALUES (34, 'R4-C');
INSERT INTO bit.gun (id, gun_name) VALUES (35, 'SASG-12');
INSERT INTO bit.gun (id, gun_name) VALUES (36, 'SG CQB');
INSERT INTO bit.gun (id, gun_name) VALUES (37, 'SMG 11');
INSERT INTO bit.gun (id, gun_name) VALUES (38, 'Super 90');
INSERT INTO bit.gun (id, gun_name) VALUES (39, 'UMP45');
INSERT INTO bit.gun (id, gun_name) VALUES (40, '416-C Carbine');

commit;